spring:
  profiles:
    active: development

---

spring:
  profiles: development
  address: localhost:8080
  data:
    mongodb:
      uri: mongodb://localhost/blogger
      repositories:
        enabled: true

---

spring:
  profiles: production
  address: localhost:8080
  data:
    mongodb:
      uri: mongodb://localhost/blogger
      repositories:
        enabled: true