spring:
  profiles:
    active: development

---

spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

---

spring:
  profiles: development
  address: localhost:8080
  data:
    mongodb:
      uri: mongodb://localhost/blogger
      repositories:
        enabled: true

---

spring:
  profiles: production
  address: localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/sp_intellimeet
    username: root
    password: igdefault
  jpa:
    hibernate:
     ddl-auto: update
multipart:
  maxFileSize: 1024Mb